import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      'coverage/**',
      '.vercel/**',
      // Generated by `prisma generate` — regenerated from the schema, never edited by hand
      'apps/api/src/libs/modules/database/generated/**',
    ],
  },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [js.configs.recommended, ...tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        // Resolves each file to the tsconfig that owns it, which is what makes the
        // type-aware rules below (no-floating-promises, no-misused-promises) possible.
        projectService: {
          // Tooling config files sit outside every app's `tsconfig.json` because they must not
          // be compiled into `dist`. They are still linted, and typechecked separately through
          // `apps/api/tsconfig.node.json`.
          allowDefaultProject: ['apps/api/prisma.config.ts'],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // TypeScript already reports unknown identifiers, and it knows about DOM and Node
      // globals per workspace — no `globals` package needed.
      'no-undef': 'off',

      'no-restricted-syntax': [
        'error',
        {
          selector: 'TSEnumDeclaration',
          message: 'Use an `as const` object with a derived union type instead of a TS enum.',
        },
      ],

      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],

      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
);
